name: Squash
on:
  push:
    branches: [xr]
permissions:
  contents: write
jobs:
  dispatch:
    name: Dispatch
    env:
     # GITHUB_TOKEN: ${{ secrets.SQUASH1 }}
      INPUT_REPO_TOKEN: GITHUB_TOKEN
      INPUT_BRANCH: main
    runs-on: ubuntu-24.04
    container:
      image: elixir:1.16.3-otp-26
    strategy:
      matrix:
        repo: ['dragonhunt02/godot']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: fix
          fetch-depth: 0
      - name: Dispatch to workflow 
        run: |
            #sudo apt install -y tree git
            #elixir
            git status
            

            git log -n 5
            git reset --soft HEAD~21
            mix local.hex --force
            mix deps.get
            mix format

            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Fix docker development image, add env validation and small fixes'
            git log -n 5
            git status
            git push -f
            exit 1
