name: Squash
on:
  push:
    branches: [xr]
permissions:
  contents: write
jobs:
  dispatch:
    name: Dispatch
    env:
      #GITHUB_TOKEN: abcd
      #${{ secrets.SQUASH1 }}
      INPUT_REPO_TOKEN: GITHUB_TOKEN
      INPUT_BRANCH: main
    runs-on: ubuntu-24.04
 #   container:
  #    image: elixir:1.16.3-otp-26
    strategy:
      matrix:
        repo: ['dragonhunt02/godot']
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: api-fix
          fetch-depth: 0
      - name: Dispatch to workflow 
        run: |
            installs_dir=$HOME/.elixir-install/installs
            export PATH=$installs_dir/otp/27.1.2/bin:$PATH
            export PATH=$installs_dir/elixir/1.18.2-otp-27/bin:$PATH
            echo "PATH=${PATH}" >> $GITHUB_ENV

      - name: Dispatch to workflow 
        run: |

            #git diff origin/patch1
            #exit 1
            
            sudo apt install -y tree git
            
            #sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
            #sudo apt update
            #sudo apt install -y elixir erlang
            
            curl -fsSO https://elixir-lang.org/install.sh
            sh install.sh elixir@1.16.3 otp@26.2.5.6
            rm install.sh
            installs_dir=$HOME/.elixir-install/installs
            export PATH=$installs_dir/otp/26.2.5.6/bin:$PATH
            export PATH=$installs_dir/elixir/1.16.3-otp-26/bin:$PATH
            echo "PATH=${PATH}" >> $GITHUB_ENV
            

            #cd /
            echo "$PATH"
            #find -type d -name ".elixir-install"
            #tree -a $HOME/.elixir-install/
            #iex
            git status
            

            git log -n 5
            git reset --soft HEAD~2

            #rm .github/workflows/test.yml
            
            #mix local.hex --force
            #mix deps.get
            #mix format

            git config --global user.email "jackhunt43@libero.it"
            git config --global user.name "dragonhunt02"
            git add -A
            git commit -a -m 'Implements admin/avatar/maps/profile/session/shards/registration apis and small fixes'
            git log -n 5
            git status
            git push -f
            exit 1
