name: Uro Development x86_64

on:
  push:
    branches: [api]
  pull_request:
    branches: [master]

jobs:
  build:
    timeout-minutes: 6
    runs-on: ubuntu-24.04
 #   container:
  #    image: elixir:1.16.3-otp-26

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update -y
          sudo apt install -y openssl ca-certificates
          export CURL_SSL_BACKEND=openssl
          export CURL_SSL_VERSION=max_tls1_2
          mv .env.example .env
          mv frontend/.env.example frontend/.env
          # timeout 5m docker compose up
          # docker compose -f docker-compose.development.yml up -d
          docker compose up -d
          sleep 1m
          URO_ID=$( docker ps --format "{{.ID}} {{.Image}}" | awk '$2 ~ /^.*-uro/ {print $1}' )
          docker exec ${URO_ID} mix run priv/repo/test_seeds.exs
          sleep 10s
          curl -v -L http://0.0.0.0:80/
          curl -v -L http://0.0.0.0:80/api/v1/health
          curl -v -i -X POST -H "Content-Type: application/json" -d '{"username":"adminuser","password":"adminpassword"}' http://0.0.0.0:80/api/v1/login
          curl -v -L http://0.0.0.0:80/api/v1/maps
          curl -v -L http://0.0.0.0:80/api/v1/admin
          echo "Run wget"
          #wget --no-check-certificate --secure-protocol=TLSv1_2 https://0.0.0.0:443/
          echo "Run curl"
          #curl -v -k -L https://0.0.0.0:443/
          exit 1
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y postgresql inotify-tools sudo
          sudo -u postgres initdb -D /var/lib/postgresql/data
          sudo -u postgres psql -c "CREATE DATABASE vsekai;"
          sudo -u postgres psql -c "CREATE USER vsekai WITH ENCRYPTED PASSWORD 'vsekai';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE vsekai TO myuser;"
          timeout 2m sudo -u postgres pg_ctl -D /var/lib/postgresql/data -l logfile start

          apt install -y build-essential erlang-dev curl

      - name: Set up Elixir
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install CockroachDB
        run: |
          curl -s https://binaries.cockroachdb.com/cockroach-v23.2.0-rc.1.linux-amd64.tgz | tar xvz
          mkdir -p ${{ runner.temp }}/cockroach
          cp cockroach-v23.2.0-rc.1.linux-amd64/cockroach ${{ runner.temp }}/cockroach/
          echo "${{ runner.temp }}/cockroach" >> $GITHUB_PATH

      - name: Start CockroachDB
        run: |
          cockroach start-single-node --insecure --background

      - name: Wait for CockroachDB to be ready
        run: |
          until cockroach sql --execute="SELECT 1" --insecure; do sleep 1; done

      - name: Install dependencies
        run: mix deps.get

      - name: Compile code
        run: mix compile

      - name: Run tests
        continue-on-error: true
        id: test_step
        run: |
          set -e
          chmod +x elixir_mvsqlite/rust_src/target/release/mvstore
          export RUST_LOG=error
          elixir_mvsqlite/rust_src/target/release/mvstore --data-plane 127.0.0.1:7000 --admin-api 127.0.0.1:7001 --metadata-prefix mvstore-test --raw-data-prefix m --auto-create-namespace --cluster /etc/foundationdb/fdb.cluster &
          sleep 1
          curl http://localhost:7001/api/create_namespace -d '{"key":"uro_dev.sqlite3","metadata":""}'
          sleep 1
          MIX_ENV=test mix ecto.setup
          MIX_ENV=test mix run priv/repo/test_seeds.exs
          mix test | tee test_output.txt; test ${PIPESTATUS[0]} -eq 0

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_output.txt

      - name: Parse and check test results
        continue-on-error: true
        if: always()
        run: |
          echo "Parsing test results..."
          TEST_OUTPUT=$(grep -oP '\d+ tests, \K\d+(?= failures)' test_output.txt)
          echo "TEST_FAILURES=$TEST_OUTPUT" >> $GITHUB_ENV

          if [ "$TEST_OUTPUT" -le 102 ]; then
            echo "Test failures are within the acceptable range."
          else
            echo "Too many test failures: $TEST_OUTPUT"
            exit 1
          fi

      - name: Check formatted code
        run: mix format --check-formatted

      - name: Run server
        run: |
          # mix do compile, phx.digest
          mix uro.apigen
          MIX_ENV=prod
          timeout 3m iex -S mix do ecto.migrate, phx.servermix
        
